version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: agwenchez
      POSTGRES_DB: biz_resolve
      POSTGRES_PASSWORD: Agwenchez254
    networks:
      - bizzresolveapi
  test-db:
    image: postgres:13
    ports:
      - 5441:5432
    environment:
      POSTGRES_USER: agwenchez
      POSTGRES_DB: biz_resolve
      POSTGRES_PASSWORD: Agwenchez254
    networks:
      - bizzresolveapi
networks:
  bizzresolveapi: